# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0003_auto_20160819_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('tavelstart', models.DateField()),
                ('travelend', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n1', to='loginapp.Userlog')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n2', to='loginapp.Userlog')),
            ],
            managers=[
                ('UserManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
