# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='tavelstart',
            new_name='travelstart',
        ),
    ]
