# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20160819_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user2',
        ),
        migrations.AlterField(
            model_name='trip',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='loginapp.Userlog'),
        ),
    ]
