# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20160819_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user1',
        ),
    ]
