# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20160819_1009'),
        ('demoapp', '0004_remove_trip_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginapp.Userlog'),
            preserve_default=False,
        ),
    ]
