# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20160819_1009'),
        ('demoapp', '0005_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='traveller',
            field=models.ManyToManyField(related_name='traveller', to='loginapp.Userlog'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='loginapp.Userlog'),
        ),
    ]
