# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20160818_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='email',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userlog',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='last_name',
        ),
    ]
